language: ruby
rvm:
  - 2.2.2
  - ruby-head
env:
  matrix:
    - RAILS_VERSION=4.2.4
    - RAILS_VERSION=master
matrix:
  allow_failures:
    - env: RAILS_VERSION=master
    - rvm: ruby-head
before_install: gem install bundler -v 1.10.6
install:
  - bundle install --retry=3
script:
  - bundle exec rake
  - bundle exec rubocop

addons:
  code_climate:
    repo_token: FIXME
